meta_product_name: "Tennis Now"
meta_title: "Tennis Now - Find your tennis partner"
meta_description: "Tennis Now is a location-based social search mobile app that allows users to like (swipe right) or dislike (swipe left) other users, and allows users to chat and plan tennis match."
meta_image: "tennis.png"                           # Une image dans votre dossier app/assets/images/
